### ISSUE TITLE
When service is not found, error message is not helpfull.

### ISSUE THREAD

**Issue by medjedovicm** [sasjs/adapter#113]
SAS Viya:  
![image](https://user-images.githubusercontent.com/18329105/94681903-76b1c580-0324-11eb-98d6-4bb8b76e7a10.png)
  
SAS 9: (response actually includes `Stored process not found`)  
![image](https://user-images.githubusercontent.com/18329105/94681939-80d3c400-0324-11eb-9ae7-36decd66ee64.png)

Ideally, response details would include message like: `Service not found on the server.`

---
Example of reponse object:

```
error: {
  message: 'Service not found on the server.',
  details: { serviceUrl: 'common/someService' },
  raw: {}
}
```

**Comment by allanbowe** [comment]
Good point.  It would also be nice (to aid debugging) to state which service was not found (sasProgramPath)
