### ISSUE TITLE
Public access denied error is not handled when trying to log in

### ISSUE THREAD

**Issue by medjedovicm** [sasjs/adapter#150]
![image](https://user-images.githubusercontent.com/18329105/98696928-a537ad00-2374-11eb-9958-d30e7b30cd4d.png)

**Comment by YuryShkoda** [comment]
@medjedovicm please provide steps to reproduce.

**Comment by allanbowe** [comment]
for this we need a user who is not in any SAS groups.  It's a SAS 9 problem
