### ISSUE TITLE
logon fails after session expires when prompted for administrator groups (reported)

### ISSUE THREAD

**Issue by allanbowe** [sasjs/adapter#222]
Not yet confirmed but we have reports that during an active session, when the token expires, the redirect to the login screen is breaking when the user is in the admin group (so, prompted to add the admin groups).

So, the adapter is not handling the admin prompt on token expiry.

**Comment by krishna-acondy** [comment]
@allanbowe @medjedovicm I believe this can also be closed as it's been fixed in a PR from a while ago.

**Comment by allanbowe** [comment]
good spot, closing
