### ISSUE TITLE
web approach request should be adding the context parameter and upload file is not adding the debug parameter nor context parameter

### ISSUE THREAD

**Issue by medjedovicm** [sasjs/adapter#308]

**Comment by krishna-acondy** [comment]
@medjedovicm @allanbowe Can this be closed now?

**Comment by allanbowe** [comment]
Yes I believe so.  @medjedovicm - when making commit messages, you can use the syntax "Closes #308" to auto close issues on merge

**Comment by allanbowe** [comment]
The _debug thing should be covered by #170
