### ISSUE TITLE
SASWORK is not being parsed correctly

### ISSUE THREAD

**Issue by medjedovicm** [sasjs/adapter#327]
![image](https://user-images.githubusercontent.com/18329105/115564555-d8358380-a2b8-11eb-9848-c9f9f2a5aeba.png)

**Comment by allanbowe** [comment]
The tables appear in an object called WORK in the response (when _debug=131), but these are not making it through to the REQUESTS window in DC

![image](https://user-images.githubusercontent.com/4420615/121864886-0c03b700-cd06-11eb-87ac-01515470d881.png)
