### ISSUE TITLE
Webpack fails to create a tarball

### ISSUE THREAD

**Issue by YuryShkoda** [sasjs/adapter#396]
To reproduce:
1.  create a tarball in `@sasjs/utils`
2. in `@sasjs/adapter` install dependency from a tarball of `@sasjs/utils`
3. run `npm run package:lib`

**Comment by krishna-acondy** [comment]
Looks like this is working okay after we updated our dependencies. Closing this now.

https://user-images.githubusercontent.com/2980428/124076887-bdad2280-da3e-11eb-8972-0240af3a449e.mov
