### ISSUE TITLE
Perform token expiry validation when polling job state

### ISSUE THREAD

**Issue by allanbowe** [sasjs/adapter#403]
Currently there is no token expiry validation when _polling_ job state, which can result in an endless loop if the token expires during execution of a Viya job

The method should be updated to accept both access and refresh tokens, so that a new token can be obtained in the case of expiry

**Comment by krishna-acondy** [comment]
We will need to implement something similar to what we have in the CLI here:
https://github.com/sasjs/cli/blob/main/src/utils/auth.ts#L41

This will require the client ID and secret to be passed in as well, or stored in the adapter config.
