### ISSUE TITLE
On Viya, when calling APIs, the _debug parameter is not passed to the correct section

### ISSUE THREAD

**Issue by medjedovicm** [sasjs/adapter#420]
![image](https://user-images.githubusercontent.com/4420615/122047116-6c6b2500-cde8-11eb-81d3-77046c524e85.png)

The `_debug` variable should be placed in the`variables` property.

**Comment by allanbowe** [comment]
When constructing the object used to create the Job Request, the _DEBUG value should be passed in the `variables` section (not `arguments`).

To test whether this is successful, look at the `_DEBUG` value in the response when submitting any sasjs request.
