### ISSUE TITLE
Deploy service pack if folder exist should return message instead of raw response/error

### ISSUE THREAD

**Issue by medjedovicm** [sasjs/adapter#429]

**Comment by medjedovicm** [comment]
Potentially related to #245

**Comment by YuryShkoda** [comment]
Currently if `force` attribute hasn't been used and the folder already exists, `@sasjs/adapter` doesn't provide a clear message, but just `Error while executing callback in handleError. Request failed with status code 409.`.
`@sasjs/adapter` should respond with the following error message in such case `Error while executing callback in handleError. Request failed with status code 409. An item named "services" of type "Folder" already exists in the folder "project". To override, please set "isForced" to "true".`.
