### ISSUE TITLE
sasjs-test tests are failing on SAS 9

### ISSUE THREAD

**Issue by allanbowe** [sasjs/adapter#468]
These should all be green:

![image](https://user-images.githubusercontent.com/4420615/125459311-cb341cf6-3d63-4207-8b18-6e6195385cfb.png)

As part of the work to fix this, we should also add an auto-deploy (for both SAS 9 and SAS Viya) of the sasjs-test app to a unique location, and put the URL into the relevant github PR

**Comment by sabhas** [comment]
all tests are passing.
![screencapture-sas-analytium-co-uk-8343-sabhas-sasjs-tests-2022-02-24-15_26_32](https://user-images.githubusercontent.com/82647447/155506678-6209947e-a3c5-46f2-bbb9-7aa3801b9c77.png)
