### ISSUE TITLE
Viya login process is bloated

### ISSUE THREAD

**Issue by allanbowe** [sasjs/adapter#470]
When running a web login on Viya there are far too many requests

To reproduce:

```bash
sasjs create demo -t minimal
cd demo
sasjs auth
sasjs cbd -t viya
```

Open the link, log out (in a seperate browser), then log in (with dev tools open)

The following requests are presented:
![image](https://user-images.githubusercontent.com/4420615/125746433-cac8b0c6-b5eb-4299-a933-385eb2846f07.png)

Some observations (may / may not be helpful):

* SASDrive is being called, which implies there is a missing redirect_uri somewhere
* We are using /identities as a check to see if we are logged in.  Perhaps `/SASJobExecution/csrf` would be a more useful endpoint
* We have a logout as part of the login.  @medjedovicm  - can you remember the reason for this?

Situations we need to handle:

* Login when session expired - eg after a period of inactivity (from all connected sessions), 15 mins or more
* Login when already logged in (#303)
* Login when logged out (eg from another tab)
* Login as part of a callback

**Comment by medjedovicm** [comment]
That is the product of our handling the scenarios that were failing. Logout on login was to clear the cookies and clear any leftover.
