### ISSUE TITLE
on startup the serverType value should be written to the log

### ISSUE THREAD

**Issue by allanbowe** [sasjs/adapter#54]
I was just debugging an app configured for SAS9 that was calling Viya

Turned out the `serverType` was defined as `servertype`

We should write message to the log on adapter instantiation to display key values (such as servertype, serverUrl etc) for faster debugging, eg:

```
The SASjs Adapter has been instantiated!  The following default values are set:
  serverUrl:
  serverType:
  debug:
  (if Viya we can show the extra variables)
To override the defaults, simply pass an updated config in the request method.
```

**Comment by krishna-acondy** [comment]
@allanbowe Should we only do this if `debug` is `true`?

**Comment by allanbowe** [comment]
I'd say no - this will typically happen only once (on app startup) and the fact that debug is not set can be the cause of some issues

**Comment by allanbowe** [comment]
Closing this - now we use the adapter extensively in the CLI, where it is instantiated with each request, to add this would result in too much logging
