### ISSUE TITLE
support special missing values

### ISSUE THREAD

**Issue by allanbowe** [sasjs/adapter#607]
A SAS numeric variable can support 28 different types of null value!  ie, `.`, `._` and `.a`->`.`z`.  These are often used to represent the different reasons why the variable is missing.

The adapter needs to be able to receive, store, and send back these null values.  On the SAS side, they will be sent as a string.  On the JS side they will be handled as a special type, and then sent back (without quotes) in the upload CSV, as follows:

Response JSON example:
```
{
  "sometable": [
    {"var1":"string", "var2":232,"nullvar":".a"},
    {"var1":"string", "var2":232,"nullvar":44.44},
    {"var1":"string", "var2":232,"nullvar":".b"},
    {"var1":"string", "var2":232,"nullvar":44.44}
  ]
}
```

Request CSV example:
```
var1:$char4 var2:best. nullvar:best.
string,232,.a
string,232,44.44
string,232,.b
string,232,44.44
```

**Comment by allanbowe** [comment]
The sort order for missings is noted here:  https://www.pauldickman.com/sastips/missing/

Reproduced:
![image](https://user-images.githubusercontent.com/4420615/147710860-55b094f7-498c-4b02-ae7f-661f54baeb27.png)

**Comment by allanbowe** [comment]
Once these previous changes are merged ^^ it will be possible to test the special missings using the adapter test suite.  Just create a test that sends data in the following format:

```json
{
  "sometable": [
    {"var1":"string", "var2":232,"nullvar":"A"},
    {"var1":"string", "var2":232,"nullvar":"B"},
    {"var1":"string", "var2":232,"nullvar":"_"},
    {"var1":"string", "var2":232,"nullvar":0}
  ]
}
```

The adapter should convert the `"A"`, `"B"` and `"_"` to `.a`, `.b` and `._` respectively.

We also need some mechanism to signal to the adapter that `nullvar` is a "special numeric" column (not a character column).

**Comment by YuryShkoda** [comment]
@allanbowe, how adapter should convert `"nullvar":0`?

**Comment by allanbowe** [comment]
It would be zero.  Basically:
* any number = the number
* `null` = `'.'`
* `_` and `A` through `Z` = `._` and `.A` -> `.Z`

**Comment by allanbowe** [comment]
Also, as just discussed.  If a "special missing" column contains ONLY the special missing values (ie, `A` and `B`) then the current version of the adapter will not be able to detect (from the values) whether it is a `$char1.` or `best.`.

So - we are going to need to introduce table properties on the javascript side.  This will be achieved through the use of an additional object containing the relevant variables formats, eg as follows:

```json
{
  sometable: [
    { var1: 'string', var2: 232, nullvar: 'A' },
    { var1: 'string', var2: 232, nullvar: 'B' },
    { var1: 'string', var2: 232, nullvar: '_' }
  ],
  SOMETABLE_properties:{formats:{var1:'$char6.',nullvar: 'best.'}}
}
```

Those properties will be optional (note that `var2` is not passed above).  Where a property is not explicitly passed, the format should be derived from the values.
