### ISSUE TITLE
Sasjs-tests failed on SAS9 (special missings)

### ISSUE THREAD

**Issue by VladislavParhomchik** [sasjs/adapter#624]
![image](https://user-images.githubusercontent.com/83717836/151935278-b2f426ce-72d4-45a8-9c2e-3ef99cdbe79b.png)

**Comment by allanbowe** [comment]
This is only an issue with special SAS missing numerics support

**Comment by medjedovicm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [utils](https://trello.com/c/tyUNWJva/378-utils)
