### ISSUE TITLE
Request data input validation improvements

### ISSUE THREAD

**Issue by medjedovicm** [sasjs/adapter#722]
In the case from the screenshot below, the adapter is not properly handling the `undefined` field.
Instead, an uncaught JavaScript error occurs.

## Input data
![image](https://user-images.githubusercontent.com/18329105/174289776-81bc4d03-df97-4ff8-b1fd-e0583621f2bc.png)

## Result
![image](https://user-images.githubusercontent.com/18329105/174290054-73317448-a991-4989-bdd9-f90b4a9828ac.png)

**Comment by allanbowe** [comment]
Expected behaviour - adapter should abort (with a helpful message, indicating the source attribute) whenever an attribute is `undefined`

**Comment by allanbowe** [comment]
Potentially links #740
