### ISSUE TITLE
Is there a way to esacpe special chars

### ISSUE THREAD

**Issue by rudvfaden** [sasjs/adapter#739]
I have some data that contains a new line chars , carriage returns and parentheses. Is there a way to escape them so the json is valid?

`blablabla. \r\n bla bla (som info)`

I would like something like 
`blablabla. \\r\\n bla bla \(som info\)`

**Comment by allanbowe** [comment]
Hi Rud - this should happen automatically.  Can you give an example of what you are trying to achieve?  Are you talking about preparing a properly escaped input JSON data object?

**Comment by rudvfaden** [comment]
My mistake. Turned out I had a substitute char `1A` in my data.

**Comment by allanbowe** [comment]
Ok!  Will close the issue then :-)
