### ISSUE TITLE
Error with request

### ISSUE THREAD

**Issue by rudvfaden** [sasjs/adapter#740]
I am getting an ERROR trying to pass some data to the adapter. I have this function.

```ts
  save() {

    let myData = this.dataejers.map((row: dataRows) => {
      return { FREKVENS: row.FREKVENS }
    });
    console.log(myData)
    this.sasService.request('common/updatedata', myData).then(() => {

    })
  }
```

My data has one col.

![image](https://user-images.githubusercontent.com/2445577/180443794-234c4826-4749-4bd4-b658-079472ba6f91.png)

I am getting this error:

```
ERROR Error: Uncaught (in promise): r: {"error":{"message":"First letter of table should be alphabet or underscore.","details":""}}
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:25535:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:21)
    at invokeTask (zone.js:1661:18)
```

Any idea of what is wrong?

**Comment by allanbowe** [comment]
Hi Rud - your data object should contain a series of table objects.  The name of each object will become your SAS table name.

Each table object contains an array of row objects.

The stringified JSON should look like this (assuming your table is called "sdfvc" and your column is "FREKVENS":

```json
{
	"sdfvc": [{
		"FREKVENS": "PRIMO_BANKDAG_MDR"
	}, {
		"FREKVENS": "PRIMO_BANKDAG_MDR"
	}, {
		"FREKVENS": "PRIMO_BANKDAG_MDR"
	}]
}
```

**Comment by allanbowe** [comment]
Hi @rudvfaden - we've updated the adapter to give a more helpful error message when this issue occurs.

**Comment by rudvfaden** [comment]
Do you have a suggestion on how to get this returned from a html table?

fre. 22. jul. 2022 15.30 skrev Allan Bowe ***@***.***>:

**Comment by allanbowe** [comment]
Hi @rudvfaden - this is a question best suited for the SASjs Support channel, as it's not specifically adapter related:  https://matrix.to/#/#sasjs:4gl.io

Will look to get you an answer there

**Comment by rudvfaden** [comment]
Old issue. You can close it.
