### ISSUE TITLE
Login: if browser set in different languages than EN the connection doesn't work

### ISSUE THREAD

**Issue by saramartinelli1992** [sasjs/adapter#760]
When using sasjs to perform a redirected login from a WebApp to SAS9, if the browser language (and consequently the SAS language) is not set to English, then the login process doesn't work.

Here the reference for Spanish:
![image](https://user-images.githubusercontent.com/100193908/191696292-ea61de72-1097-416d-acfa-7b18b25f9d76.png)

**Comment by allanbowe** [comment]
Hi @saramartinelli1992 - we've refactored this part and added a specific test for Spanish locale:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/4420615/192749150-0958fb4c-74d7-4692-88d8-78c842b5df74.png">

Do let us know if it's working ok, or if there are any other issues.
