### ISSUE TITLE
Sending data with POST method on node v18 fails

### ISSUE THREAD

**Issue by medjedovicm** [sasjs/adapter#771]
Error details:

![image](https://user-images.githubusercontent.com/18329105/203547620-355da7d2-3c35-4986-85df-09e5f4724edc.png)

**Comment by sabhas** [comment]
It fails on v18 too.

**Comment by sabhas** [comment]
via Hubstaff
User: Sabir Hassan

Project: SASjs Adapter - https://app.hubstaff.com/projects/2310873
Date Range: 01/31/23 - 02/01/23
Work session total: 7:06:54
Billable: Yes

Grand total: 7:06:54

**Comment by sabhas** [comment]
via Hubstaff
User: Sabir Hassan

Project: SASjs Adapter - https://app.hubstaff.com/projects/2310873
Date Range: 02/01/23 - 02/01/23
Work session total: 3:44:20
Billable: Yes

Grand total: 10:51:14
