### ISSUE TITLE
sas9 default login

### ISSUE THREAD

**Issue by allanbowe** [sasjs/adapter#776]
We have seen issues with `loginMechanism: 'Default'` on http SAS 9 EBI installs

We should deploy a web app to SAS 9 EBI and test / confirm that this configuration is working.  This will involve first logging out, then logging in from the application directly.

**Comment by allanbowe** [comment]
After testing this on an EBI image (http connection) the login mechanism IS working.  So we were unable to reproduce..

**Comment by sabhas** [comment]
via Hubstaff
User: Sabir Hassan

Project: SASjs Adapter - https://app.hubstaff.com/projects/2310873
Date Range: 01/31/23 - 01/31/23
Work session total: 0:00:08
Billable: Yes

Grand total: 0:00:08
