### ISSUE TITLE
If the server url contains `.do` on SAS9` it gets stripped

### ISSUE THREAD

**Issue by medjedovicm** [sasjs/adapter#786]
`sas.domain.com` - will get broken by the `replace()` function.
#### Example
`sasomain.com`  

https://github.com/sasjs/adapter/blob/60d3ff2d3904c721446cb442f96528ad7c9c159e/src/auth/AuthManager.ts#L242  
https://github.com/sasjs/adapter/blob/60d3ff2d3904c721446cb442f96528ad7c9c159e/src/auth/AuthManager.ts#L351

**Comment by allanbowe** [comment]
For reference, this should be explicitly for serverType "SAS9" (as not relevant for "SASJS")
