### ISSUE TITLE
sasjs login to sas fails when userLongName = unknown

### ISSUE THREAD

**Issue by saramartinelli1992** [sasjs/adapter#796]
I'm using sasjs to connect my webapp and SAS and I recently started facing an issue.
When I open my Web App, if I'm not connected the sasjs login returns userLongName = unknown as displayed in the picture below, while userName is empty

![image](https://user-images.githubusercontent.com/100193908/229117840-33a3c159-4c89-4e47-89b2-3e8ff5e19c25.png)

The fact that userLongName is not empty makes sasjs think that I'm connected and it does not appear the login mask.
As a side note, if I login in another SAS app and then open my webapp, sasjs is able to correctly recognize my user

**Comment by allanbowe** [comment]
Thanks for raising @saramartinelli1992 - we'll investigate this asap

**Comment by sabhas** [comment]
@saramartinelli1992 which version of the adapter are you using? The latest version is 4.2.1. If you are not using the latest, please update the version and check if the problem persists.

**Comment by saramartinelli1992** [comment]
@sabhas I was using a previous version, I now tested the lates one and I see the window for login, but it shows the following
![image](https://user-images.githubusercontent.com/100193908/229145179-76a22ae6-f92f-455f-9ea2-b0daa71b3673.png)

**Comment by allanbowe** [comment]
Following a call with @saramartinelli1992 we discovered that SAS9 M8 no longer redirects from SASLogon/home (but it does redirect in SAS9 M7, also Viya 4)

We did some tests and it seems the logon is consistent across versions when just using /SASLogon, we also did a build and tested this change on M8 and that worked fine.  PR to follow.

Relevant commits:  

* https://github.com/sasjs/adapter/commit/d9c27efa8d5aa81dd58126141ba63b32b218a1d4
* https://github.com/sasjs/adapter/commit/830a907bd1c6546ed74fa969546b37681cc7967f

**Comment by allanbowe** [comment]
@all-contributors please add @saramartinelli1992 for UserTesting and Platform
