### ISSUE TITLE
JES Job Execution: Failed requests on each execution attempt

### ISSUE THREAD

**Issue by krishna-acondy** [sasjs/adapter#97]
There seem to be two failed requests on each job execution attempt:
* One for uploading tables as files
* One for posting the actual job

This is likely CSRF related and should be easily fixed as we're handling it okay in the other approaches.
![image](https://user-images.githubusercontent.com/2980428/93575415-83800200-f991-11ea-91af-4de48ed15b7e.png)

**Comment by medjedovicm** [comment]
This means it does not use token that is stored, instead it is retrying every request with goal of capturing it?
